// compose.go — Master 端依 SlaveRecord 動態產生 Slave 端 docker-compose.yml。
//
// 設計目標:使用者在 Master UI 加完節點後,直接複製貼到 Slave 機器即可運作,
// 不需手動填 NodeID/Token。
//
// 注意:Master URL 由前端傳入(因為 Master 不知道自己的對外 URL),
// 後端僅做基本欄位代換 + YAML escape。
package cluster

import (
	"fmt"
	"strings"

	"wstunnel/internal/config"
)

// ComposeOptions 是產生 compose 時前端可調整的參數。
type ComposeOptions struct {
	NodeID         string
	MasterURL      string // 例:https://master.example.com:9090
	PublicAddr     string // 給使用者連的對外位址
	SkipTLSVerify  bool
	IncludeDNSTT   bool
	HeartbeatSec   int
}

// GenerateSlaveCompose 對指定 NodeID 產生一份 docker-compose.yml。
// 找不到該 node 會回傳 error。
func GenerateSlaveCompose(opt ComposeOptions) (string, error) {
	cfg := config.Get()
	if cfg == nil {
		return "", fmt.Errorf("config not initialized")
	}
	cfg.Lock.RLock()
	rec, ok := cfg.Slaves[opt.NodeID]
	cfg.Lock.RUnlock()
	if !ok {
		return "", fmt.Errorf("node %s not found", opt.NodeID)
	}

	if opt.MasterURL == "" {
		return "", fmt.Errorf("master_url required")
	}
	if opt.HeartbeatSec <= 0 {
		opt.HeartbeatSec = 30
	}

	// 簡易 YAML string 字面值 escape:用單引號包起並把單引號 doubled
	q := func(s string) string { return "'" + strings.ReplaceAll(s, "'", "''") + "'" }

	skip := "false"
	if opt.SkipTLSVerify {
		skip = "true"
	}

	var sb strings.Builder
	fmt.Fprintf(&sb, "# WSTunnel Slave node: %s\n", rec.NodeName)
	fmt.Fprintf(&sb, "# Generated by Master — do NOT edit secrets by hand\n")
	fmt.Fprintf(&sb, "# Master 上看到的節點 ID: %s\n\n", rec.NodeID)
	sb.WriteString("services:\n")
	sb.WriteString("  wstunnel:\n")
	sb.WriteString("    image: ghcr.io/treehd/wstunnel:latest\n")
	fmt.Fprintf(&sb, "    container_name: wstunnel-%s\n", rec.NodeID)
	sb.WriteString("    restart: always\n")
	sb.WriteString("    ports:\n")
	sb.WriteString("      - \"80:80\"\n")
	sb.WriteString("      - \"443:443\"\n")
	sb.WriteString("      - \"9090:9090\"\n")
	sb.WriteString("    environment:\n")
	sb.WriteString("      - CLUSTER_ROLE=slave\n")
	fmt.Fprintf(&sb, "      - MASTER_URL=%s\n", q(opt.MasterURL))
	fmt.Fprintf(&sb, "      - MASTER_TOKEN=%s\n", q(rec.Token))
	fmt.Fprintf(&sb, "      - NODE_ID=%s\n", q(rec.NodeID))
	fmt.Fprintf(&sb, "      - NODE_NAME=%s\n", q(rec.NodeName))
	if opt.PublicAddr != "" {
		fmt.Fprintf(&sb, "      - PUBLIC_ADDR=%s\n", q(opt.PublicAddr))
	}
	fmt.Fprintf(&sb, "      - HEARTBEAT_INTERVAL_SEC=%d\n", opt.HeartbeatSec)
	fmt.Fprintf(&sb, "      - SKIP_MASTER_TLS_VERIFY=%s\n", skip)
	sb.WriteString("    volumes:\n")
	sb.WriteString("      - ./data:/app/data\n")
	sb.WriteString("    healthcheck:\n")
	sb.WriteString("      test: [\"CMD\", \"bash\", \"-c\", \"echo > /dev/tcp/127.0.0.1/80 2>/dev/null\"]\n")
	sb.WriteString("      interval: 10s\n")
	sb.WriteString("      timeout: 3s\n")
	sb.WriteString("      retries: 5\n")

	if opt.IncludeDNSTT {
		sb.WriteString("\n  dnstt:\n")
		sb.WriteString("    image: ghcr.io/treehd/wstunnel-dnstt:latest\n")
		fmt.Fprintf(&sb, "    container_name: dnstt-%s\n", rec.NodeID)
		sb.WriteString("    restart: always\n")
		sb.WriteString("    ports:\n")
		sb.WriteString("      - \"53:5353/udp\"\n")
		sb.WriteString("    environment:\n")
		sb.WriteString("      - DNSTT_DOMAIN=\n")
	}
	return sb.String(), nil
}
